[package]
name = "morva-mcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "morva-mcp"
path = "src/main.rs"

[dependencies]
morva-core = { path = "../morva-core" }
morva-machine = { path = "../morva-machine" }
